title: Storywork Seminare
email: ulfpomerenke@web.de
description: Storywork Seminare – Menschen bewegen mit Geschichten.
url: "https://storywork-seminare.de"
github_username:  storywork

# Build settings
markdown: kramdown