backend:
  name: git-gateway
  branch: master
media_folder: "img"
collections:
  - name: "sites"
    label: "Seiten"
    folder: "/"
    create: false
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}